### ISSUE TITLE
Bottom Card

### ISSUE THREAD

**Issue by Jordanthfc7** [DBuit/sidebar-card#10]
Could someone please share their config for the bottomCard.

I can't seem to get it working, even when I try a simple entities card, nothing shows in the side menu.

**Comment by nathbullen** [comment]
I've got the same issue, I feel like it could possibly be broken with newer versions of HA?

**Comment by DBuit** [comment]
Hi guys,

This is just a simple example to get 3 buttons.
This should work, let me know if you check your browser developer console and see if there is an error and share it with me :)

```
bottomCard:
        type: horizontal-stack
        cardOptions:
          cards:
            - type: "custom:button-card"
              color_type: card
              color: rgb(255, 255, 255)
              icon: mdi:home
            - type: "custom:button-card"
              color_type: ccard
              color: rgb(255, 255, 255)
              icon: mdi:lightbulb
```
