### ISSUE TITLE
white sidebar

### ISSUE THREAD

**Issue by stibe881** [DBuit/sidebar-card#12]
white sidebar

for me the sidebar is only shown in white. what am I doing wrong?
![1](https://user-images.githubusercontent.com/24219649/82894270-a2760680-9f52-11ea-9395-6fbd1466ec02.png)
![2](https://user-images.githubusercontent.com/24219649/82894342-ba4d8a80-9f52-11ea-8173-c518068f6282.png)

**Comment by DBuit** [comment]
Hi,

Check out this: https://github.com/DBuit/sidebar-card#style
You need to add style to your configuration and change `--sidebar-background: #FFF;` to the color you want it is default white

**Comment by stibe881** [comment]
@DBuit 
but with the code in the printscreen should dicoh menu items be displayed? or is standard white writing on a white background?

**Comment by stibe881** [comment]
@DBuit 
the problem is not the color. The problem is that the menu entries are not shown.

**Comment by DBuit** [comment]
Ok, no should be black but you could try set: --sidebar-text-color: #000;
Or check the developer tools to see if there are errors?

**Comment by stibe881** [comment]
@DBuit 
No errors.

**Comment by DBuit** [comment]
Can you share your config as text so i can copy pase it :)

**Comment by stibe881** [comment]
@DBuit 
i tried with this:
sidebar:
  style: |
    :host {
        --sidebar-background: #737373;
        --sidebar-text-color: #000;
        --face-color: #FFF;
        --face-border-color: #FFF;
        --clock-hands-color: #000;
        --clock-seconds-hand-color: #FF4B3E;
        --clock-middle-background: #FFF;
        --clock-middle-border: #000;
    }



and with this:
sidebar:
  sidebarMenu:
    - action: navigate
      active: true
      name: Home
      navigation_path: /lovelace/default_view
    - action: navigate
      name: Licht
      navigation_path: /lovelace/licht
    - action: navigate
      name: Olga
      navigation_path: /lovelace/saugroboter
    - action: navigate
    - action: navigate
      name: Musik
      navigation_path: /lovelace/spotify
    - action: navigate
      name: Garage
      navigation_path: /lovelace/garage
    - action: toggle
      entity: light.licht_buro
      icon: 'mdi:led-strip-variant'
      name: Licht Büro
      state: light.beganegrond

**Comment by DBuit** [comment]
It works for me:
````
sidebar:
  sidebarMenu:
    - action: navigate
      active: true
      name: Home
      navigation_path: /lovelace/default_view
    - action: navigate
      name: Licht
      navigation_path: /lovelace/licht
    - action: navigate
      name: Olga
      navigation_path: /lovelace/saugroboter
    - action: navigate
    - action: navigate
      name: Musik
      navigation_path: /lovelace/spotify
    - action: navigate
      name: Garage
      navigation_path: /lovelace/garage
    - action: toggle
      entity: light.licht_buro
      icon: 'mdi:led-strip-variant'
      name: Licht Büro
      state: light.beganegrond
```
