### ISSUE TITLE
Sidebar not loading

### ISSUE THREAD

**Issue by madansu** [DBuit/sidebar-card#20]
Hi,

I have the module installed via HACS. 
I currently have multiple dashboards, and am trying to setup the newest iteration of dashboards in a brand new dashboard.

My main dashboard is UI controlled, and my configuration.yaml has the following entries - 

```
lovelace:
  mode: storage
  # Now Add YAML Dashbaords
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Scratch
      icon: mdi:script
      show_in_sidebar: true
      filename: scratch.yaml
```

The problem I have is that my sidebar does not show up. Any pointers on what the issue could be ?
Here is the content of my scratch.yaml

```
resources:
  url: /hacsfiles/sidebar-card/sidebar-card.js
  type: module
custom_header: {}
sidebar:
  title: "Hi!"
  digitalClock: true
  twelveHourVersion: true
  date: true
  hideTopMenu: true
  showTopMenuOnMobile: true
  template: |
    <li>
      {% if now().hour  < 5 %} Good Night {{'\U0001F634'}}
      {% elif now().hour < 12 %} Good Morning {{'\u2615\uFE0F'}}
      {% elif now().hour < 18 %} Good Afternoon {{'\U0001F44B\U0001F3FB'}}
      {% else %} Good Evening {{'\U0001F44B\U0001F3FB'}}{% endif %}
    </li>  
  style: |
    :host {
        --sidebar-background: #FFF;
        --sidebar-text-color: #000;
        --face-color: #FFF;
        --face-border-color: #FFF;
        --clock-hands-color: #000;
        --clock-seconds-hand-color: #FF4B3E;
        --clock-middle-background: #FFF;
        --clock-middle-border: #000;
    }
  width:
    mobile: 20
    tablet: 25
    desktop: 20
  sidebarMenu:
    - action: navigate
      navigation_path: /lovelace/home
      name: Home
      active: true
    - action: navigate
      navigation_path: /lovelace/home1
      name: Home1
      active: true
title: Home
views: []
```

Thanks in advance !

**Comment by Beaty59** [comment]
Having the same issue when going between dashboards, I have to refresh the tablet to get the sidebar-card to load. Any ideas yet?

**Comment by MapoDan** [comment]
Ciao

Same issue here. I've installed through HACS too, but nothing is showing up..
My setup includes multiple dashboards too.

```yaml
sidebar:
  title: 'This is SIDEBAR'
  clock: false
  date: true
  dateFormat: 'DD/MM/YYYY'
  hideTopMenu: true
  width:
    mobile: 800
    tablet: 800
    desktop: 800
  sidebarMenu:
    action: more-info
    entity: sensor.cameretta
```
