### ISSUE TITLE
Sidebar Menu doesn't follow external URL changes

### ISSUE THREAD

**Issue by bluesheep** [DBuit/sidebar-card#28]
When an external service changes the url of the page, the Sidebar doesn't change its highlighted section.

I change the URL using browser_mod service

```
service: browser_mod.navigate
data:
  navigation_path: /study-tablet/lighting
  deviceID:
    - browser_study-tablet
```

My sidebar config is as follows:

```
  sidebarMenu:
    - action: navigate
      navigation_path: /study-tablet/info
      name: Info
      active: true
    - action: navigate
      navigation_path: /study-tablet/lighting
      name: Lighting
      active: true
```
