### ISSUE TITLE
hideTopMenu isn't working

### ISSUE THREAD

**Issue by blake-sherrill** [DBuit/sidebar-card#3]
Everytime I add hideTopMenu it doesn't work. No error in the logs. The sidebar just completely disappears. Tried different browsers. If I edit "hideTopMenu: true" out then everything is back. 
```
resources:
  - type: module
    url: /hacsfiles/sidebar-card/sidebar-card.js
sidebar:
  title: Sidebar
  digitalClock: true
  hideTopMenu: true
  sidebarMenu:
    - action: navigate
      navigation_path: /lovelace/home
      name: Home
      active: true
    - action: navigate
      navigation_path: /lovelace/garage
      name: Garage
      active: true
```

P.S. Thanks for fixing the firefox issue, works great other then this so far.
