### ISSUE TITLE
Sidebar Not Loading Consistently

### ISSUE THREAD

**Issue by 400HPMustang** [DBuit/sidebar-card#33]
I just installed this yesterday and the issue I'm having is that sidebar doesn't consistently load. I can reload the the page a few times and the sidebar will show. When I try to navigate to one of the other paths in the dashboard (lights, security, etc) from the sidebar I get bounced back to my default dashboard which is just the default lovelace view. The header bar does however work correctly.

```
sidebarMenu:
    - action: navigate
      navigation_path: /lovelace-tablet/main
      name: Home
      active: true
    - action: navigate
      navigation_path: /lovelace-tabet/lights
      name: Lights
    - action: navigate
      navigation_path: /lovelace-tablet/security
      name: Security
    - action: navigate
      navigation_path: /lovelace-tablet/media
      name: Media
```
