### ISSUE TITLE
! Read this - There are better alternatives

### ISSUE THREAD

**Issue by rcjkierkels** [DBuit/sidebar-card#37]
This was a great idea if you are just like me looking for a sidebar. But as the readme says it's work in progress and has many issues. I tried to fix a couple of them but I lost my interest seeing that the effort of other developers making PR's with partial solutions for the issues did not activate the developer. I was looking for another solution and found that the grid-layout from https://github.com/thomasloven/lovelace-layout-card is a way better way to do it.

Use pure css to split up your view into a sidebar part and a main part. Setup once, use the power of includes to reuse your sidebar on all other dashboards and you have an issue free, more powerful/customizable solution.

I rebuild the entire sidebar (including clock, bottom card and templating) using grid layouts, card-mod and now I am free of all issues. Perfect control of sidebar width on all devices. No disappearing images and so on.

Just a tip, for if you consider using this.

**Comment by kfcook** [comment]
@rcjkierkels is there any way you can post some sample code to do this in a repo? My CSS skills aren't super iffy so I'd have a hard time starting from scratch. Any samples would be greatly appreciated! I was excited to find this add-on, but it's disappointing that it isn't maintained.

**Comment by rcjkierkels** [comment]
@kfcook yeah sure. Here is a example lovelace dashboard with a sidebar that can be included in every view or just the views you want. Look here https://github.com/thomasloven/lovelace-layout-card for more examples:

```
panel: true
path: test
title: Test
cards:
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: 20% 30px auto
      grid-template-rows: auto
      grid-template-areas: |
        "sidebar . main"
      mediaquery:
        "(max-width: 600px)":
          grid-template-columns: 100%
          grid-template-areas: |
            "sidebar"
            "main"
        "(max-width: 800px)":
          grid-template-columns: 50% 50%
          grid-template-areas: |
            "sidebar"
            "main"
    cards:
      - !include ../components/sidebar.yaml
      - type: entities
        entities:
          - light.bedroom
        title: Bedroom
        view_layout:
          grid-area: main
```

The sidebar.yaml could look like this:

```
type: vertical-stack
view_layout:
  grid-area: sidebar
cards:
  - !include ../cards/clock.yaml
  - type: weather-forecast
    entity: weather.buienradar
    show_forecast: true
  - type: horizontal-stack
    cards:
      - type: picture-elements
        image: /local/media/people/person1.jpg
        entity: person.one
        state_filter:
          not_home: grayscale(100%) brightness(50%)
        style:
          border-radius: 20%
        elements:
          - type: state-icon
            entity: person.one
            icon: mdi:home
            style:
              left: 86%
              top: 86%
              background-color: black
              border-radius: 20%
              "--paper-item-icon-color": white
      - type: picture-elements
        image: /local/media/people/two.jpg
        entity: person.two
        state_filter:
          not_home: grayscale(100%) brightness(50%)
        style:
          border-radius: 20%
        elements:
          - type: state-icon
            entity: person.two
            icon: mdi:home
            style:
              left: 86%
              top: 86%
              background-color: black
              border-radius: 20%
              "--paper-item-icon-color": white
```

And you can make your own simple clock like this:

```
type: custom:mod-card
card:
  type: custom:html-template-card
  ignore_line_breaks: true
  content: |
    {% set dagen = ["Zondag", "Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag"] %}
    {% set maand = ["Jan", "Feb", "Maart", "April", "Mei", "Juni", "Juli", "Aug", "Sep", "Okt", "Nov", "Dec"] %}
    <h2>{{states('sensor.time')}}</h2>
    <div class="date">{{dagen[now().strftime('%w') | int]}}, {{ now().strftime('%-d') }} {{ maand[now().strftime('%-m') | int] }} {{ now().strftime('%Y') }}</div>
card_mod:
  style: |
    ha-card {
      background: none;
      box-shadow: none;
    }
    h2 {
      font-size: 60px;
    }
    .date {
      font-size: 20px;
      margin-top: -20px;
      color: #aaa8a8
    }
```

**Comment by kfcook** [comment]
Thanks @rcjkierkels ! This works well.

I really like how the sidebar card has a split tone background between the sidebar and the main section. I know this is probably a simple question, but I can't seem to figure out how to replicate that with this setup. Any ideas?

**Comment by rcjkierkels** [comment]
@kfcook Try wrapping the vertical-stack card in de sidebar.yaml with this:

```
type: custom:mod-card
card_mod:
  style: |
    ha-card {
      background-color: #2d2d2d;
      height: 100%;
      padding: 15px;
      width: 100%;
    }
card:
  type: vertical-stack
  ....
```

You will need https://github.com/thomasloven/lovelace-card-mod to get this working.
There might be other ways. I am also not an css expert. But this should get you started :-)

**Comment by bckthomas** [comment]
Hi @rcjkierkels 
I am also interested to migrate to lovelace-card but how do you manage the menu in the sidebar?
Thanks

**Comment by wtrbuit** [comment]
We have just merged a PR from another developer who fixed a number of issues. We couldn't get around working on this project due to time. We will try to keep it a bit more up to date from now on. I am closing this "issue" and if you want specific enhancements of issues fixed please open a new one. Thank you for your patience if you are still with us :)

**Comment by steveuk23** [comment]
> 

Hi i know this is old but was hoping you could help.
I've not had any luck using this sidebar card as it just remains black and nobody seems to be using the community page now to answer my question.
So anyway i tried using your method , does it still work as i set it all up as you described and created a sidebar.yaml and clock.yaml ect.
And then i copy your dashboard code into my new dashboard by using the Raw configuration menu but i'm getting a error about YAMLException: unknown tag !<!include>
And from looking around people are saying i'm unable to use the !include in the raw configuration editor is that correct?
If so how do i get around it as i don't know how to do the other method.
Thanks
Oh sorry another point you put "- !include ../cards/clock.yaml" where are you actually storing them yaml files ? is it in the local folder so local/cards/clock.yaml

**Comment by bckthomas** [comment]
Hi @steveuk23 
Here is my config for my home page : 
`
 views:
  - type: custom:grid-layout
    path: 0
    layout:
    cards:
      - !include ui-lovelace/sidebar.yaml
      - type: grid
      - !include ui-lovelace/footer.yaml

  - !include ui-lovelace/plex.yaml
  - !include ui-lovelace/meteo.yaml
  - !include ui-lovelace/aspirateur.yaml
  - !include ui-lovelace/nhl.yaml
  - !include ui-lovelace/calendrier.yaml
  - !include ui-lovelace/volets.yaml
  - !include ui-lovelace/arrosage.yaml
  - !include ui-lovelace/systeme.yaml
`

Ui lovelace sidebar.yaml : 
`
type: vertical-stack
view_layout:
  grid-area: sidebar
cards:
  - type: custom:button-card
    entity: sensor.template_sidebar
    template: sidebar_template

  - type: vertical-stack
    cards:
      - type: 'custom:button-card'
        layout: icon_label
        template: button_menu_button
        tap_action:
          action: navigate
          navigation_path: /lovelace/0
        icon: mdi:home
        variables:
           path: 0
        label: Accueil
        show_label: true
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start

      - type: 'custom:button-card'
        layout: icon_label
        template: button_menu_button
        tap_action:
          action: navigate
          navigation_path: /lovelace/plex
        icon: mdi:plex
        variables:
           path: plex
        label: Plex
        show_label: true
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start

      - type: 'custom:button-card'
        layout: icon_label  
        template: button_menu_button       
        tap_action:
          action: navigate
          navigation_path: /lovelace/meteo
        icon: mdi:weather-cloudy
        variables:
           path: meteo
        label: Météo
        show_label: true
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start

      - type: 'custom:button-card'
        layout: icon_label
        template: button_menu_button
        tap_action:
          action: navigate
          navigation_path: /lovelace/aspirateur
        icon: mdi:robot-vacuum
        variables:
           path: aspirateur
        label: Aspirateur
        show_label: true
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start

      - type: 'custom:button-card'
        layout: icon_label
        template: button_menu_button
        tap_action:
          action: navigate
          navigation_path: /lovelace/nhl
        icon: mdi:hockey-sticks
        variables:
           path: nhl
        label: NHL
        show_label: true
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start

      - type: 'custom:button-card'
        layout: icon_label
        template: button_menu_button
        tap_action:
          action: navigate
          navigation_path: /lovelace/calendar
        icon: mdi:calendar
        variables:
           path: calendar
        label: Calendrier
        show_label: true
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start

      - type: 'custom:button-card'
        layout: icon_label
        template: button_menu_button
        tap_action:
          action: navigate
          navigation_path: /lovelace/volets
        icon: hass:blinds
        variables:
           path: volets
        label: Volets
        show_label: true
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start

      - type: 'custom:button-card'
        layout: icon_label
        template: button_menu_button
        tap_action:
          action: navigate
          navigation_path: /lovelace/arrosage
        icon: mdi:sprinkler-variant
        variables:
           path: arrosage
        label: Arrosage
        show_label: true
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start

      - type: 'custom:button-card'
        layout: icon_label
        template: button_menu_button
        tap_action:
          action: navigate
          navigation_path: /lovelace/systeme
        icon: mdi:server
        variables:
           path: systeme
        label: Système
        show_label: true
        extra_styles: |
          @keyframes update {
            10%, 90% {
              transform: translateY(-1px);
            }

            20%, 80% {
              transform: translateY(2px);
            }

            30%, 50%, 70% {
              transform: translateY(-2px);
            }

            40%, 60% {
              transform: translateY(2px);
            }
          }
        styles:
          card:
            - height: 60px
          label:
            - justify-self: start
          icon:
            - animation: '[[[ if (states["binary_sensor.sidebar_update_color"].state == "on") return "update 2.5s ease-out infinite"; ]]]'
`

Ui lovelace for another page (example with plex page) : 
`
type: custom:grid-layout
path: plex
title: Plex

layout:
cards:
  - !include sidebar.yaml

  - type: "custom:upcoming-media-card"
    ...

  - !include footer.yaml
`

Hope it helps !
I will publish a git repo in the next few days with all my config

**Comment by rcjkierkels** [comment]
Hi @steveuk23 

FIrst of all I am using Visual Studio Code addon to write my yaml configurations. Maybe the RAW editor does some optimalisation checks. If you can use Visual Studio Code.

I have the the **clock.yaml** in the directory: /config/lovelace/cards/clock.yaml
The **sidebar.yaml** is in the directory /config/lovelace/components/sidebar.yaml
And my view is in the directory: /config/lovelace/views/overview.yaml

**Comment by steveuk23** [comment]
@rcjkierkels 
Thanks that will help me loads, quite a bit of modifying ha ha..
I think my problem is I did all my dashboard through the UI and I don't have the views in a Yaml file like you do in "config/lovelace/views/overview.yaml" so I'm unable to edit them in Vscode only in the Raw configuration editor which I've now found out is classed as UI which doesn't allow the use of !include.
I have had this before with something else and wanted to swap but couldn't work out how to.
I'll have a look when I've finished work.
Thanks

**Comment by steveuk23** [comment]
> Hi @steveuk23 Here is my config for my home page : ` views:
> 
> * type: custom:grid-layout
>   path: 0
>   layout:
>   cards:
>   
>   * !include ui-lovelace/sidebar.yaml
>   * type: grid
>   * !include ui-lovelace/footer.yaml
> * !include ui-lovelace/plex.yaml
> * !include ui-lovelace/meteo.yaml
> * !include ui-lovelace/aspirateur.yaml
> * !include ui-lovelace/nhl.yaml
> * !include ui-lovelace/calendrier.yaml
> * !include ui-lovelace/volets.yaml
> * !include ui-lovelace/arrosage.yaml
> * !include ui-lovelace/systeme.yaml
>   `
> 
> Ui lovelace sidebar.yaml : ` type: vertical-stack view_layout: grid-area: sidebar cards:
> 
> * type: custom:button-card
>   entity: sensor.template_sidebar
>   template: sidebar_template
> * type: vertical-stack
>   cards:
>   
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/0
>     icon: mdi:home
>     variables:
>     path: 0
>     label: Accueil
>     show_label: true
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/plex
>     icon: mdi:plex
>     variables:
>     path: plex
>     label: Plex
>     show_label: true
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/meteo
>     icon: mdi:weather-cloudy
>     variables:
>     path: meteo
>     label: Météo
>     show_label: true
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/aspirateur
>     icon: mdi:robot-vacuum
>     variables:
>     path: aspirateur
>     label: Aspirateur
>     show_label: true
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/nhl
>     icon: mdi:hockey-sticks
>     variables:
>     path: nhl
>     label: NHL
>     show_label: true
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/calendar
>     icon: mdi:calendar
>     variables:
>     path: calendar
>     label: Calendrier
>     show_label: true
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/volets
>     icon: hass:blinds
>     variables:
>     path: volets
>     label: Volets
>     show_label: true
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/arrosage
>     icon: mdi:sprinkler-variant
>     variables:
>     path: arrosage
>     label: Arrosage
>     show_label: true
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>   * type: 'custom:button-card'
>     layout: icon_label
>     template: button_menu_button
>     tap_action:
>     action: navigate
>     navigation_path: /lovelace/systeme
>     icon: mdi:server
>     variables:
>     path: systeme
>     label: Système
>     show_label: true
>     extra_styles: |
>     @Keyframes update {
>     10%, 90% {
>     transform: translateY(-1px);
>     }
>     ```
>     20%, 80% {
>       transform: translateY(2px);
>     }
>     
>     30%, 50%, 70% {
>       transform: translateY(-2px);
>     }
>     
>     40%, 60% {
>       transform: translateY(2px);
>     }
>     ```
>     
>     
>         
>           
>         
>     
>           
>         
>     
>         
>       
>     }
>     styles:
>     card:
>     - height: 60px
>     label:
>     - justify-self: start
>     icon:
>     - animation: '[[[ if (states["binary_sensor.sidebar_update_color"].state == "on") return "update 2.5s ease-out infinite"; ]]]'
>     `
> 
> Ui lovelace for another page (example with plex page) : ` type: custom:grid-layout path: plex title: Plex
> 
> layout: cards:
> 
> * !include sidebar.yaml
> * type: "custom:upcoming-media-card"
>   ...
> * !include footer.yaml
>   `
> 
> Hope it helps ! I will publish a git repo in the next few days with all my config

Thanks for this.
I'm still quite new to this so going through it all now,
you have the include like "!include ui-lovelace/plex.yaml" are they actually UI created dashboards or yaml as it;s confusing me seeing the UI there and the yaml lol
I have added the storage option to my configuration.yaml and defined a yaml dashboard is that how you have done all them ones ?
Sorry for all the dumb questions ha ha

**Comment by steveuk23** [comment]
@rcjkierkels @bckthomas 
Hi guys sorry to ask again hopefully this is the last time.
So I've now got a Yaml based dashboard showing with example data etc.
I then pasted your dashboard code from above into the same Yaml file but no sidebar shows up only the original few buttons.
The sidebar.yaml and clock.yaml are in the correct folders.
Could you look so my full code for the dashboard and see where I've gone wrong.
Thanks
```
panel: true
path: test
title: Test
cards:
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: 20% 30px auto
      grid-template-rows: auto
      grid-template-areas: |
        "sidebar . main"
      mediaquery:
        "(max-width: 600px)":
          grid-template-columns: 100%
          grid-template-areas: |
            "sidebar"
            "main"
        "(max-width: 800px)":
          grid-template-columns: 50% 50%
          grid-template-areas: |
            "sidebar"
            "main"
    cards:
      - !include /config/lovelace/components/sidebar.yaml
      - type: entities
        entities:
          - light.bedroom
        title: Bedroom
        view_layout:
          grid-area: main
views:
    # View tab title.
  - title: Example
    # Unique path for direct access /lovelace/${path}
    path: example
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.sara_mobile
          - device_tracker.steve_mobile_2
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home

        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.dining_room_lamp

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.kitchen_lamp
          - entity: light.dining_room_lamp
            # Override the name to use
            name: LR Lights

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.

```
