### ISSUE TITLE
Not working in 2023.4

### ISSUE THREAD

**Issue by horve000** [DBuit/sidebar-card#83]
Stopt working after updating to homeassistant 2023.4

**Comment by blaiser72** [comment]
Stop working after update home assistant version 2023.4

**Comment by igmsoft** [comment]
Resources should no longer be added to the dashboard configuration but can be added in the dashboard config panel. Tried adding it under dashboard resources  but no luck!

**Comment by DBuit** [comment]
Im updating at this moment en will see how to fix it and update the card if needed

**Comment by DBuit** [comment]
I just updated the card, it looks all good for me. let me know if you still got issues!

**Comment by DBuit** [comment]
There is an issue with the update. if you go to other page it redraws the sidebar inside the old one so you get multiple sidebars....
Working on this issue.

**Comment by sanderabbink** [comment]
Haha, just updated, and found the same issue. Also it is not possible to drag the original sidebar from the left top corner.

**Comment by sekonicpr** [comment]
> I just updated the card, it looks all good for me. let me know if you still got issues!

stop working on my HA 2023.3.6 after 0.1.9 update.

**Comment by horve000** [comment]
Just updated  and have the same issue, multiple sidebars. Also the layout is not the same as before. Also if the sidebar is showing the top bar is now over the side bar and the rest of the cards. If the sidebar is not showing everything looks fine.

**Comment by Andreasjkoch** [comment]
I just updated, everything works again for me

**Comment by igmsoft** [comment]
Everything works again for me, thank you [DBuit](https://github.com/DBuit)

**Comment by horve000** [comment]
Update to 0.1.9.1 Fixed the multiple sidebars for me. Thank you @DBuit .

**Comment by AlxSZP** [comment]
Hi @DBuit I had the sidebar working just fine, the update broke it. After to 0.1.9.1 I still don't see it. Is there anything else I need to do to make it work?
- I checked the resource is there
- My dashboard didn't change, so it's all there as well

**Comment by rodrigogbs** [comment]
> Hi @DBuit I had the sidebar working just fine, the update broke it. After to 0.1.9.1 I can see it now; however, now IO'm noticing a new issue:
> ![image](https://user-images.githubusercontent.com/76796365/230492577-9c172833-2fa3-4c4d-b606-35a5330a9c49.png)
> The top bar is eating the top of my dashboard, any help will be appreciated

Same here

**Comment by Begie1605** [comment]
After update....everything works again as expected....thnx @DBuit

**Comment by olaoups** [comment]
> > Hi @DBuit I had the sidebar working just fine, the update broke it. After to 0.1.9.1 I can see it now; however, now IO'm noticing a new issue:
> > ![image](https://user-images.githubusercontent.com/76796365/230492577-9c172833-2fa3-4c4d-b606-35a5330a9c49.png)
> > The top bar is eating the top of my dashboard, any help will be appreciated
> 
> Same here



> Hi @DBuit I had the sidebar working just fine, the update broke it. After to 0.1.9.1 I can see it now; however, now IO'm noticing a new issue: ![image](https://user-images.githubusercontent.com/76796365/230492577-9c172833-2fa3-4c4d-b606-35a5330a9c49.png) The top bar is eating the top of my dashboard, any help will be appreciated

Same problem here...

* The "margin-top:0!important;" on the #view element is overwriting the default CSS property of HA.
* It works great with the kiosk-mode enable but not on standard views (without kiosk-mode).

![image](https://user-images.githubusercontent.com/12000405/230577820-5924095b-ef88-43ef-9426-fd26e585ca1c.png)

**Comment by gffa325** [comment]
Same problem here.

> Same problem here. ![problem kioskmode](https://user-images.githubusercontent.com/6498608/230584514-e438a9ec-aae5-444f-a46b-a45d81bf0412.png)

**Comment by almighty059** [comment]
I have the same problem with the top missing.

**Comment by leonidfeldman1977** [comment]
Same for me

**Comment by sekonicpr** [comment]
Same here!

![image](https://user-images.githubusercontent.com/40529944/230784318-c8b4da51-3ccb-4082-afe4-74394800ce41.jpeg)

**Comment by sparment** [comment]
Same here. I just installed this custom component yesterday. I noticed an error in my system log... not sure if this is related to the issue noted here or not:

http://192.168.1.33:8123/local/community/sidebar-card/sidebar-card.js:18067:88 TypeError: null is not an object (evaluating 'header.offsetHeight')
http://192.168.1.33:8123/local/community/sidebar-card/sidebar-card.js:18067:89 Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')

**Comment by michaelkaravani** [comment]
I also have the same problem
I use floorplan card
And in the log this is what appears

<img src="https://i.ibb.co/rdZ7mw6/009.jpg" style="max-width: 100%;">

and in my HA log 
```

Logger: frontend.js.latest.202304061
Source: components/system_log/__init__.py:257
First occurred: 9 באפריל 2023 בשעה 22:48:04 (18 occurrences)
Last logged: 13:26:43

http://192.168.5.34:8123/hacsfiles/sidebar-card/sidebar-card.js?hacstag=2418255740184:18067:89 Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
http://192.168.5.34:8123/frontend_latest/25408-l9JqVOI8CmQ.js:1:1482 Uncaught RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()
http://192.168.5.34:8123/hacsfiles/sidebar-card/sidebar-card.js?hacstag=2418255740191:18067:89 Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
```

**Comment by DBuit** [comment]
Hello everyone,

Im working on fix for the header that is over the sidebar when you dont hide the top header of hass.
Also fixing the bottomcard position when you dont hide the top header.

Think i will release today.

**Comment by DBuit** [comment]
Just released update

**Comment by horve000** [comment]
> Just released update

All works like before again. Thank you !!

**Comment by sekonicpr** [comment]
After performing the update it leaves me a small bar in the sidebar.![image](https://user-images.githubusercontent.com/40529944/231149895-7e59defa-af21-45f7-9c69-6199c4792c55.jpeg)

**Comment by Murcin86** [comment]
Confirm - 1.9.2 fix that gap :)

**Comment by blaiser72** [comment]
Confirm bug fixes on 1.9.2.

**Comment by theglus** [comment]
I'm still experiencing issues on 1.9.2.

```
background: var(--background-image)
kiosk_mode:
  hide_header: true
sidebar:
  hideTopMenu: true
  digitalClock: true
  twelveHourVersion: true
  period: false
  date: true
  dateFormat: dddd, MMMM Do
  width:
    mobile: 0
    tablet: 25
    desktop: 25
  sidebarMenu:
    - action: navigate
      navigation_path: "/lovelace/default_view"
      name: "Home"
      icon: "mdi:home"
      active: true
    - action: navigate
      navigation_path: "/lovelace/winston"
      name: "Winston"
      icon: "mdi:robot-vacuum-variant"
      active: true
    - action: navigate
      navigation_path: "/lovelace/ha"
      name: "System"
      icon: "mdi:home-assistant"
      active: true
  template: |
    <li>The air quality in Dogpatch is {{states('sensor.u_s_air_pollution_level')}} with an AQI of {{states('sensor.aqi')}}.</li>
  style: |
    :host {
        --sidebar-background: rgba(0,0,0,.3);
    }
button_card_templates: !include_dir_named includes/lovelace/button_card_templates
decluttering_templates: !include_dir_named includes/lovelace/decluttering_templates
title: Loft
views: !include_dir_list includes/lovelace/views
```

![Missing Sidecard](https://user-images.githubusercontent.com/2943783/231295803-1bdc3acc-888d-487f-9146-f789e8da3e1d.png)

**Comment by sparment** [comment]
I'm still having issue with 1.9.2:

![image](https://user-images.githubusercontent.com/65453555/231309734-5a96daa0-31c2-48be-b208-290ac478f7a0.png)

**Comment by sparment** [comment]
Clearing my cache seemed to fix the issue.

**Comment by BadgerLoaf** [comment]
> After performing the update it leaves me a small bar in the sidebar.![image](https://user-images.githubusercontent.com/40529944/231149895-7e59defa-af21-45f7-9c69-6199c4792c55.jpeg)

I'm having the same issue on my tablet running Fully, though not on my MacOS browser.

I'm also no longer getting my bottom cards since 2023.4.... anyone else having that issue?

**Comment by sekonicpr** [comment]
Same for me on button card even after a clear cache.

**Comment by sparment** [comment]
Same

**Comment by DBuit** [comment]
@BadgerLoaf , @sekonicpr , @sparment can one of you check the html of the page if the bottomcard is just not rendered or that it is positioned at some weird place?

Also the extra space on top, can you share your config of the sidebar?

**Comment by flixlix** [comment]
<img width="1512" alt="Bildschirmfoto 2023-04-13 um 13 06 18" src="https://user-images.githubusercontent.com/61006057/231740285-cb75855d-ce92-4d05-af46-d79246fd0bc7.png">
<img width="1512" alt="Bildschirmfoto 2023-04-13 um 13 06 08" src="https://user-images.githubusercontent.com/61006057/231740308-747a5025-4e4b-46d4-93ba-3e7269aa32c0.png">
I noticed the margin-top property in the developer tools...

**Comment by sekonicpr** [comment]
![image](https://user-images.githubusercontent.com/40529944/231774242-e173f8b5-725e-44a0-b878-141f95ebd7e9.jpeg)

![image](https://user-images.githubusercontent.com/40529944/231774294-644fcf51-83b4-4526-a9dd-04f19da9c3ee.jpeg)

**Comment by BadgerLoaf** [comment]
> @BadgerLoaf , @sekonicpr , @sparment can one of you check the html of the page if the bottomcard is just not rendered or that it is positioned at some weird place?
> 
> Also the extra space on top, can you share your config of the sidebar?

I suspect @sekonicpr has given you what you need, but can send some stuff over later if needed.

**Comment by sekonicpr** [comment]
Here my sidebar config

`sidebar:
  width:
    mobile: 25
    tablet: 25
    desktop: 20
  clock: false
  digitalClock: true
  twelveHourVersion: true
  period: true
  date: true
  dateFormat: DD MMMM YYYY
  sidebarMenu:
    - action: navigate
      navigation_path: main
      name: Home
      active: true
      icon: mdi:home
    - action: navigate
      navigation_path: alarm
      name: Alarm
      active: true
      icon: mdi:shield-lock-open-outline
    - action: navigate
      navigation_path: tool-room
      name: Tool Room
      active: true
      icon: mdi:home-circle-outline
    - action: navigate
      navigation_path: media_center
      active: true
      name: Media Center
      icon: mdi:music
    - action: navigate
      navigation_path: climate
      name: Climate
      icon: mdi:weather-cloudy
    - action: navigate
      navigation_path: network
      name: Network
      active: true
      icon: mdi:lan-connect
    - action: navigate
      navigation_path: system-monitor
      active: true
      name: System Monitor
      icon: mdi:chart-line
    - action: navigate
      navigation_path: weather
      active: true
      name: Weather
      icon: mdi:weather-hazy
  style: |
    .sidebarMenu li.active {
     background-color: rgba(5, 9, 111, 0.6)!important;
     border-radius: 40px!important;
     font-weight: bold!important;
     }
    .sidebarMenu li.active ha-icon {
        color: orange!important;
    }
    :host {
        --sidebar-background: #160b24;
        --sidebar-text-color: #BDC1C6;
        --face-color: #312F2F;
        --face-border-color: #615E5E;
        --clock-hands-color: #0C0808; !important
        --clock-seconds-hand-color: #B11F00; !important
        --clock-middle-background: #474545; !important
        --clock-middle-border: #615E5E; !important
    }

    h1.digitalClock {
        font-size: 50px !important;
        font-weight: 400 !important;
        cursor: default;
        padding-bottom: 0px;
        padding-top: 0px
        font-family: 'Product Sans'
    }
    h2.date {
        text-align: center;
        font-size: 34px;
        font-weight: 400 !important;
        font-family: 'Product Sans'
    }
    h1{
        text-align: center;
        font-size: 25px;
    }
    period{
        text-align: right;
        font-size: 8px;
        font-variant: large-caps
        text-transform: capitalize
    }
  bottomCard:
    type: horizontal-stack
    cardOptions:
      cards:
        - type: weather-forecast
          entity: weather.home
          show_forecast: true
          style: |
            ha-card {
              background: transparent;
              border-radius: 0px; 
              margin: 0px !important;
              padding: 0px 16px 0px !important;
              box-shadow: none !important;
              font-size: 5px !important;
              /*filter: grayscale(100%);*/
              -webkit-tap-highlight-color: transparent;
            }
            :host .content {
              flex-flow: row-reverse !important;
            }
            :host .state , :host .temp {
              font-size: 18px !important;
              font-weight: 300 !important;
            }
            .temp-attribute {
              text-align: left;
              margin-left: -78px;
            }
            ha-card .icon-image svg {
              height: 32px !important;
            }
            :host .temp-attribute span {
              font-size: 11px !important;
              top: 7px !important;
              color: rgb(156, 156, 156);
            }
    cardStyle: |
      :host {
        width: 100%;

        top: 30;
        bottom: 0;
        left: 0;
      }`

**Comment by rodrigogbs** [comment]
Guys, I don't use Kiosk Mode and the problem is happening in my installation:

![Captura de Tela 2023-04-13 às 16 37 17](https://user-images.githubusercontent.com/71797145/231865336-de8b0dc4-2ace-4168-a441-52db45baaa91.png)

Here is my sidebar config:

```
sidebar:
  hideTopMenu: true
  hideHassSidebar: false
  showTopMenuOnMobile: true
  digitalClock: true
  date: true
  dateFormat: ddd DD MMM YY
  width:
    desktop: 18
    mobile: 0
    tablet: 18
  sidebarMenu:
    - action: navigate
      name: Home
      icon: mdi:home
      navigation_path: /lovelace/home
    - action: navigate
      name: Cozinha
      icon: mdi:countertop
      navigation_path: /lovelace/cozinha
    - action: navigate
      name: Energia
      icon: mdi:lightning-bolt
      navigation_path: /lovelace/energia
    - action: navigate
      name: Escritório
      icon: mdi:chair-rolling
      navigation_path: /lovelace/escritorio
    - action: navigate
      name: Lavanderia
      icon: mdi:washing-machine
      navigation_path: /lovelace/lavanderia
    - action: navigate
      name: Quarto
      icon: mdi:baby
      navigation_path: /lovelace/quarto
    - action: navigate
      name: Sacada
      icon: mdi:balcony
      navigation_path: /lovelace/sacada
    - action: navigate
      name: Sala
      icon: mdi:sofa
      navigation_path: /lovelace/sala
    - action: navigate
      name: Suíte
      icon: mdi:seat-individual-suite
      navigation_path: /lovelace/suite
  template: |
    <li>

      Próximos Eventos:

    </li>
    <li>

      {% if as_timestamp(state_attr('calendar.visita','start_time')) >
      as_timestamp(now().strftime('%Y-%m-%d %H:%M:%S')) and
      (as_timestamp(now().strftime('%Y-%m-%d %H:%M:%S'))+43200) >
      as_timestamp(state_attr('calendar.visita','start_time')) %} {{
      state_attr('calendar.visita','message') }} - {{
      as_timestamp(state_attr('calendar.visita','start_time')) |
      timestamp_custom('%H:%M') }} {% endif %}

    </li>
    <li>

      {% if as_timestamp(state_attr('calendar.aula_ingles','start_time')) >
      as_timestamp(now().strftime('%Y-%m-%d %H:%M:%S')) and
      (as_timestamp(now().strftime('%Y-%m-%d %H:%M:%S'))+43200) >
      as_timestamp(state_attr('calendar.aula_ingles','start_time')) %} {{
      state_attr('calendar.aula_ingles','message') }} - {{
      as_timestamp(state_attr('calendar.aula_ingles','start_time')) |
      timestamp_custom('%H:%M') }} {% endif %}

    </li>
    <li>

      {% if as_timestamp(state_attr('calendar.diarista','start_time')) >
      as_timestamp(now().strftime('%Y-%m-%d %H:%M:%S')) and
      (as_timestamp(now().strftime('%Y-%m-%d %H:%M:%S'))+43200) >
      as_timestamp(state_attr('calendar.diarista','start_time')) %} {{
      state_attr('calendar.diarista','message') }} - {{
      as_timestamp(state_attr('calendar.diarista','start_time')) |
      timestamp_custom('%H:%M') }} {% endif %}

    </li>
    <li>

      {% if as_timestamp(state_attr('calendar.consulta_psicologo','start_time')) >
      as_timestamp(now().strftime('%Y-%m-%d %H:%M:%S')) and
      (as_timestamp(now().strftime('%Y-%m-%d %H:%M:%S'))+43200) >
      as_timestamp(state_attr('calendar.consulta_psicologo','start_time')) %} {{
      state_attr('calendar.consulta_psicologo','message') }} - {{
      as_timestamp(state_attr('calendar.consulta_psicologo','start_time')) |
      timestamp_custom('%H:%M') }} {% endif %}

    </li>
  style: |
    :host {
        --sidebar-background: var(--primary-background-color);
        --sidebar-text-color: var(--primary-text-color);
        --border-radius: 5px;
        --face-color: #FFF;
        --face-border-color: #FFF;
        --clock-hands-color: #000;
        --clock-seconds-hand-color: #FF4B3E;
        --clock-middle-background: #FFF;
        --clock-middle-border: #000;    
    }
    .sidebarMenu li.active {
        background-image: url('/local/sidebar_background.png');
        border-radius: 40px;
        font-weight: bold;
     }
    .digitalClock {
        padding-bottom: 5px;
        padding-top: 15px;
    }
    .digitalClock {
        color: rgba(255, 255, 255, 0.7);
        font-size: 50px ;
        font-weight: 500;
        letter-spacing: -0.05vw;
        text-align: center;
    }
    .date {
        padding-bottom: 10px;
        color: rgba(255, 255, 255, 0.3);
        font-size: 25px;
        font-weight: 300;
        text-align: center;
        letter-spacing: -0.05vw;
    }
    .template li {
        color: rgba(255, 255, 255, 0.7);
        font-size:.1.3vw;
        font-weight: 200;
        opacity: 0.3;
        letter-spacing: -0.05vw;
        text-align: center;
    }
background: var(--background-image)
title: T10A263
views:
```

**Comment by almighty059** [comment]
@BadgerLoaf I'm having the same issue and I do not see any options in the sidebar card that will allow me select devices/users for the top menu showing like the kiosk card has. 

![20230415_063236](https://user-images.githubusercontent.com/63380298/232219391-f2cdca53-0f8c-41d3-9020-fe815d76cf7f.jpg)

**Comment by olaoups** [comment]
Same issue... But it seems that this problem is relative to kiosk-mode and not to sidebar-card.

When kiosk-mode is enabled:
* The `var(--header-height)` has a value in px when calculating the `<div id="customSidebar">`
* But it has a 0px value when calculating the `<div id="view">`

Second constatation: There is an error in console log for the kiosk-mode:
`kiosk-mode.js?hacstag=497319128183:1 Uncaught TypeError: Cannot read properties of null (reading 'dataset')`

Any idea? Thanks for your help!

**Comment by sparment** [comment]
> 

@michaelkaravani I'm still having the same issue that you referenced above. Are you? Or did the update fix it for you? I'm wondering if we should be opening a separate issue.

**Comment by michaelkaravani** [comment]
> > 
> 
> @michaelkaravani I'm still having the same issue that you referenced above. Are you? Or did the update fix it for you? I'm wondering if we should be opening a separate issue.

the error in the log Update did the job it doesn't appear anymore.
I only had a problem with the floorplan card
To fix this, I canceled ```full_height: fasle``` in the [floorplan card](https://github.com/ExperienceLovelace/ha-floorplan)
And I used a layout card
```
title: floorplan
path: floorplan
type: custom:masonry-layout
layout:
  width: 730
  max_cols: 1
badges: []
```
I don't use the top bar ```hideTopMenu: true``` in [sidebar card](https://github.com/DBuit/sidebar-card)


I hope I was able to help in some way..

**Comment by sparment** [comment]
Thanks. This was helpful. I figured out the issue looks to be a setting I have in my views "panel: true"

Anyone have suggestions on an alternative to have cards spread across the entire screen?

**Comment by michaelkaravani** [comment]
You're right.
This is why I used a [layout card](https://github.com/thomasloven/lovelace-layout-card)
solve it for now
I remove this  code line ```panel: true``` and ``` type: panel```  from my view
And I set the width of the card to ```width: 730```  in the [layout card](https://github.com/thomasloven/lovelace-layout-card)
To fit my screen and I set ``` max_cols: 1``` 
```
title: floorplan
path: floorplan
type: custom:masonry-layout
layout:
  width: 730  // you need to change this 
  max_cols: 1
badges: []
```

**Comment by sparment** [comment]
Got it. Thanks

**Comment by michaelkaravani** [comment]
> I got rid of `type: panel` and `panel: true` but am still having the same issues.
> 
> Errors in my log:
> 
> * http://192.168.1.33:8123/local/community/sidebar-card/sidebar-card.js:18125:33 Uncaught TypeError: cardElement.setConfig is not a function
> * http://192.168.1.33:8123/local/community/sidebar-card/sidebar-card.js:18125:42 TypeError: cardElement.setConfig is not a function. (In 'cardElement.setConfig(card)', 'cardElement.setConfig' is undefined)

I went through my log
I don't have any such error
you can share your ```raw Configuration``` code ?

**Comment by sparment** [comment]
@michaelkaravani, attached is a truncated version of my lovelace config file. Please let me know if you see any issues...
[ui-lovelace copy.txt](https://github.com/DBuit/sidebar-card/files/11301653/ui-lovelace.copy.txt)

**Comment by michaelkaravani** [comment]
> @michaelkaravani, attached is a truncated version of my lovelace config file. Please let me know if you see any issues... [ui-lovelace copy.txt](https://github.com/DBuit/sidebar-card/files/11301653/ui-lovelace.copy.txt)

I don't see any problem with your code
Just don't understand why you have it twice
```type: vertical-stack```
one of which is empty
```
views:
  - title: "OVERVIEW"
    path: overview
    type: custom:masonry-layout
    layout:
      width: 740
      max_cols: 1
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack <-------
            cards: <------
          - type: vertical-stack
            cards:
              - type: entity-filter
                entities:
                  - binary_sensor.upstairs_motion
                  - binary_sensor.kitchen_occupancy
                  - binary_sensor.guest_room_occupancy
                state_filter:
                  - "on"
                  - "open"
                card:
                  state_color: true
                  show_state: false
                  show_header_toggle: False
                  title: "Motion Detected"
```
What version of HA are you using?
Which version of sidebar card?

**Comment by sparment** [comment]
Thanks for checking the code. The double vertical-stack was just a typo in what I posted. It's not there in my actual code.

I'm running:
Home Assistant 2023.4.6
Supervisor 2023.04.0
Sidebar Card: 0.1.9.2

**Comment by michaelkaravani** [comment]
> Thanks for checking the code. The double vertical-stack was just a typo in what I posted. It's not there in my actual code.
> 
> I'm running: Home Assistant 2023.4.6 Supervisor 2023.04.0 Sidebar Card: 0.1.9.2
> 
> Just to clarify - the issue I'm having is the bottom card does not consistently appear. And I'm getting the error in my log referenced above.

try to chabge in bottomCard ```type: vertical-stack``` to ```type: horizontal-stack```

**Comment by sparment** [comment]
Tried that. No change.

**Comment by michaelkaravani** [comment]
> Tried that. No change.

It works for me.  I don't know how else to help you. 
Maybe someone else who understands the code better than me can help.

**Comment by sparment** [comment]
Looks like the issue I am having is covered under issue #45 
I'll post over there...

**Comment by sparment** [comment]
@michaelkaravani I've determined the issue has to do with stacking of multiple cards in the bottom card.

If I use the code below I get the error:

```
bottomCard:
  type: vertical-stack
  cardOptions:
    cards:
       - type: ....
         entity: ...
```

If I don't do a vertical-stack or horizontal-stack it works fine:

```
bottomCard:
  type: ...
  entity: ...
```

However, without the stack I don't know how to do multiple cards. Are you using multiple cards in the Bottom Card section? If so, could you share your code?

**Comment by michaelkaravani** [comment]
@sparment 
i just copy your bottomCard to chack 


[for better view](https://pastecode.io/s/ohtio0yw)

```
sidebar:
  width:
    mobile: 0
    desktop: 23
  digitalClock: true
  date: true
  hideTopMenu: true
  sidebarMenu:
    - action: navigate
      navigation_path: /dashboard-tab/0
      name: ראשי
      active: true
      hold_action:
        action: none
    - action: navigate
      navigation_path: /dashboard-tab/livingroom
      name: סלון
      active: true
      hold_action:
        action: none
    - action: navigate
      navigation_path: /dashboard-tab/kitchen
      name: מטבח
      active: true
      hold_action:
        action: none
    - action: navigate
      navigation_path: /dashboard-tab/bedroom
      name: חדר שינה
      active: true
      hold_action:
        action: none
    - action: navigate
      navigation_path: /dashboard-tab/bathroom
      name: שירותים
      active: true
      hold_action:
        action: none
    - action: navigate
      navigation_path: /dashboard-tab/front-outside
      name: חוץ קדימה
      active: true
      hold_action:
        action: none
    - action: navigate
      navigation_path: /dashboard-tab/side-outside
      name: חוץ צד
      active: true
      hold_action:
        action: none
    - action: navigate
      navigation_path: /dashboard-tab/back-outside
      name: חוץ אחורה
      active: true
      hold_action:
        action: none
    - action: navigate
      navigation_path: /dashboard-tab/floorplan
      name: תוכנית קומה
      active: true
      hold_action:
        action: none
  bottomCard:
    type: horizontal-stack
    cardOptions:
      cards:
        - type: weather-forecast
          entity: weather.byt
          show_current: true
          show_forecast: true
          secondary_info_attribute: humidity
          tap_action:
            action: none
        - type: weather-forecast
          entity: weather.byt
          show_current: true
          show_forecast: true
          secondary_info_attribute: humidity
          tap_action:
            action: none
```
**----------------------------------------------------------------**
**Do not consider that there is no margin, it can be fixed**
**----------------------------------------------------------------**
![image](https://user-images.githubusercontent.com/45473667/233907859-d14fa407-7bca-4b28-997f-ce5837263974.png)
